[project]
name = "jax-gemma-1b"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jax[tpu]>=0.8.2",
    "ml-dtypes>=0.5.4",
    "numpy>=2.4.0",
    "optax>=0.2.6",
    "safetensors>=0.7.0",
    "sentencepiece>=0.2.1",
]
